blog/urls.py
from django.conf.urls import url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^post/new/$', views.post_new, name='post_new'),
    #url(r'^users/view/$', views.users_view, name='users_view'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^logout_view/$', views.logout_view, name='logout_view'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^operationalDashboard/$', views.login_operational_user, name='login_operational_user'),
    url(r'^register/$', views.register , name='register'),
    url(r'^search/$', views.searchResults, name='searchResults'),
]

dashboard/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.dashboard, name='dashboard'),
	url(r'^formReport/$', views.formcharts, name='formcharts'),
	url(r'^report/$', views.charts, name='charts'),
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from blog import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^dashboard/', include('dashboard.urls')),
    url(r'^lockers/', include('lock.urls')),
    url(r'^home/', include('blog.urls')),
]

dashboard/models.py
from __future__ import unicode_literals

from django.db import models

class Table1(models.Model):
    locker_id = models.IntegerField(primary_key=True)
    locker_name = models.CharField(db_column='Locker_name', max_length=45, blank=True, null=True)  # Field name made lowercase.
    city = models.CharField(max_length=45, blank=True, null=True)
    state = models.CharField(max_length=45, blank=True, null=True)
    pincode = models.CharField(max_length=45, blank=True, null=True)
    prime_capacity = models.CharField(max_length=45, blank=True, null=True)
    standard_capacity = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        db_table = 'table1'


class Prime(models.Model):
    key_p = models.AutoField(primary_key=True)
    locker = models.ForeignKey(Table1, on_delete=models.CASCADE)
    day0 = models.IntegerField(blank=True, null=True)
    day1 = models.IntegerField(blank=True, null=True)
    day2 = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'prime'


class Standard(models.Model):
    key_s = models.AutoField(primary_key=True)
    locker = models.ForeignKey(Table1, on_delete=models.CASCADE)
    day0 = models.IntegerField(blank=True, null=True)
    day1 = models.IntegerField(blank=True, null=True)
    day2 = models.IntegerField(blank=True, null=True)
    day3 = models.IntegerField(blank=True, null=True)
    day4 = models.IntegerField(blank=True, null=True)
    day5 = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'standard'

class Orders(models.Model):
    serial_no = models.AutoField(primary_key=True)
    locker = models.ForeignKey('Table1', on_delete=models.CASCADE)
    order_date = models.DateField()
    order_type = models.IntegerField()
    locker_used = models.IntegerField()

    class Meta:
        db_table = 'orders'

dashboard/forms.py
from django import forms
import datetime
from django.forms import ModelForm
from .models import Table1, Prime, Standard

class NewForm(ModelForm):
	user_date = forms.DateField(required=True, label='Enter date (yyyy-mm-dd)', initial=datetime.date.today)
	class Meta:
		model = Table1
		fields = ['locker_name', 'city', 'state', 'pincode']

class ChartForm(forms.Form):
	locker_id = forms.IntegerField(required=True, label='Locker ID')
	prime_or_standard = forms.CharField(required=True, label='Prime/Standard')

dashboard/views.py
from django.shortcuts import render
from .models import *
from django.db.models import Q
from datetime import date
from datetime import timedelta
from .forms import NewForm, ChartForm
#from .script import fun
from django.http import HttpResponse
from graphos.sources.simple import SimpleDataSource
from graphos.renderers.gchart import LineChart
from graphos.renderers import gchart
from graphos.sources.model import ModelDataSource

def formcharts(request):
	form_class = ChartForm()
	return render(request, 'chartForm.html', {'form':form_class})

def charts(request):
	form_class = ChartForm()
	lockerId = request.POST.get('locker_id')
	lockerType = request.POST.get('prime_or_standard')
	if lockerType.lower() == "prime":
		locker_type="Prime"
		locker = Orders.objects.filter(
	    	Q(locker_id=lockerId),Q(order_type=1)
	    ).distinct()
	else:
		locker_type="Standard"
		locker = Orders.objects.filter(
	    	Q(locker_id=lockerId),Q(order_type=2)
	    ).distinct()

	data_source = ModelDataSource(locker,fields=['order_date', 'locker_used'])
	chart = gchart.LineChart(data_source, html_id='gchart_div', options={'title': 'Locker Booking Trends'})
	context = {
		'chart': chart,
		'len':len(locker),
		'locker_id':lockerId,
		'type':locker_type
		}
	return render(request, 'charts.html', context)

def dashboard(request):
	form_class = NewForm

	if request.method == 'POST':
		form = form_class(data=request.POST)

		if form.is_valid():
			q1 = request.POST.get('locker_name')
			q2 = request.POST.get('city')
			q3 = request.POST.get('state')
			q4 = request.POST.get('pincode')
			use_date = form.cleaned_data['user_date']

			date_now = date.today()
			date_1 = date_now + timedelta(days=1)
			date_2 = date_now + timedelta(days=2)
			date_3 = date_now + timedelta(days=3)
			date_4 = date_now + timedelta(days=4)
			date_5 = date_now + timedelta(days=5)

			d={}
			if q1 != "":
				d['locker_name__iexact']=q1;
			if q2 != "":
				d['city__iexact']=q2;
			if q3 != "":
				d['state__iexact']=q3;
			if q4 != "":
				d['pincode__iexact']=q4;

			obj = Table1.objects.filter(**d).distinct()
			obj2 = list()
			obj3 = list()
			var = 0
			if use_date > date_5:
				var = 6
			elif use_date==date_now:
				var = 0
			elif use_date==date_1:
				var = 1
			elif use_date==date_2:
				var = 2
			elif use_date==date_3:
				var = 3
			elif use_date==date_4:
				var = 4
			elif use_date==date_5:
				var = 5
			elif use_date < date_now:
				var = -1

			for ob in obj:
				if var==-1:
					obj=''
					break
				for row in ob.prime_set.all():
					if (var==3) | (var==4) | (var==5) | (var==6):
						obj2.append(ob.prime_capacity)
					elif var==0:
						obj2.append(row.day0)
					elif var==1:
						obj2.append(row.day1)
					elif var==2:
						obj2.append(row.day2)
				for r in ob.standard_set.all():
					if var==6:
						obj3.append(ob.standard_capacity)
					elif var==0:
						obj3.append(r.day0)
					elif var==1:
						obj3.append(r.day1)
					elif var==2:
						obj3.append(r.day2)
					elif var==3:
						obj3.append(r.day3)
					elif var==4:
						obj3.append(r.day4)
					elif var==5:
						obj3.append(r.day5)

			ob = zip(obj, obj2, obj3)
			context = {
			"ob":ob,
			"len":len(obj)
			}
			return render(request, 'dashboard.html', context)
	return render(request, 'dashboard.html', {'form':form_class})

def rotate_day():
    fun()
    return HttpResponse('dashboard.html')

dashboard/templates/chartForm.html
<!--HTML for Admin Dashboard. Gets results from querying function 'dashboard'-->

{% extends 'home.html' %}
{% block main_content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
</script>
<div class="container">
	<h2>Generate Report</h2>
</div>
<div class="container">
	<h4>Enter lockerID and Prime/Standard for locker whose report has to be generated</h4>
</div>
<div class="container">
<table>
	<form method="post" action="{% url 'charts' %}">{% csrf_token %}
		{%for field in form%}
		<tr>
		       	<td><label><br>{{field.label_tag}}</label></td>
		        <td>{{field}}</td>
		</tr>
		{%endfor%}
		<tr>
			<td></td>
			<td><br><button type="submit" class="btn btn-warning">Generate Report</button></td>
		</tr>
	</form>
</table>
</div>
{% endblock %}

dashboard/templates/charts.html
<!--HTML for Admin Dashboard. Gets results from querying function 'dashboard'-->

{% extends 'home.html' %}
{% block main_content %}
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
    window.onload = function(){
    	document.getElementById("gchart_div").style.width="100%";
    }
</script>
{% ifequal len 0 %}
	<div class="container">
		<p>No data/lockers available for given lockerID. Please enter again!</p>
	</div>
{%else %}
	<div class="container">
		<h3>Report for {{type}} lockers of lockerID:{{locker_id}}</h3>
	</div>
	<div class="container">
		{{chart.as_html}}
	</div>
{% endifequal %}
<br>
<div class="container">
	<form style="width:100%" method="post" action="{% url 'formcharts' %}">{% csrf_token %}
		<center><button type="submit" class="btn btn-warning">Generate Another Report</button></center>
	</form>
</div>
<br><br>
{% endblock %}

dashboard/templates/dashboard.html
<!--HTML for Admin Dashboard. Gets results from querying function 'dashboard'-->
{% extends 'home.html' %}
{% block main_content %}
<style type="text/css">
form{ 
	display: table;
}
p{
	display: table-row;  
}
label, input{ 
	display: table-cell; 
}
#id_user_date{
	padding: 0px 10px;
}
</style>
<script type="text/javascript">
	window.onload=function (){
		var x = document.getElementById("id_user_date");
		x.setAttribute("type", "date");
	}
</script>
<div class="container">
	<a href = "{% url 'formcharts' %}" class="btn btn-warning">View Report</a>
</div>
<div class="container">
	<h3><strong>Search lockers by:</strong></h3>
</div>
<div class="container">
	<form method="post" action="{% url 'dashboard' %}">{% csrf_token %}
		{%for field in form%}
		<p>
		       	<label>{{field.label_tag}}</label>
		        {{field}}
		</p>
		{%endfor%}
	<br>
	<button type="submit" class="btn btn-warning">Find Lockers</button>
	</form>
</div>
<br><br>

<div class="container">
{% ifequal len 0 %}
	<p>No lockers available in the area. Please search again!</p>
{%else %}
	<table class="table">
		<tr>
			<th><center>Locker Name</center></th>
			<th><center>City</center></th>
			<th><center>State</center></th>
			<th><center>Pincode</center></th>
			<th><center>Total Lockers</center></th>
			<th><center>Prime Available</center></th>
			<th><center>Standard Available</center></th>
		</tr>
		{% for i, j, k in ob %}
			<tr>
				<td><center>{{i.locker_name}}</center></td>
				<td><center>{{i.city}}</center></td>
				<td><center>{{i.state}}</center></td>
				<td><center>{{i.pincode}}</center></td>
				<td><center>100</center></td>
				<td><center>{{j}}</center></td>
				<td><center>{{k}}</center></td>
			</tr>
		{% endfor %}
	</table>
{% endifequal %}
</div>
{% endblock %}

dashboard/templates/home.html
<!--Base HTML file-->
{%load staticfiles %}
<!DOCTYPE html>
<head>
	<link rel="icon" href="{%static 'img/favicon.jpg' %}" type="image" sizes="16x16">
	<title>Admin Dashboard</title>
	<link rel="stylesheet" type="text/css" href ="{% static 'dashboard/bootstrap-3.2.0/css/bootstrap.min.css'%}" />
  	<link rel="stylesheet" type="text/css" href ="{% static 'dashboard/bootstrap-3.2.0/css/bootstrap-theme.min.css' %}" />
  	<link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  	<link rel="stylesheet" type="text/css" href ="{% static 'dashboard/index.css'%}" />
  	<link rel="stylesheet" type="text/css" href ="{% static 'dashboard/dashboard.css'%}" />
	<meta charset="utf-8">
</head>
<style type="text/css">
input{
	padding: 5px 2px;
}
</style>
<body>
	<div class="page-header">
		{%if user.is_authenticated%}
       		<a href = "{% url 'logout_view' %}" class="logout_button">
            	<span class="glyphicon glyphicon-log-out" data-toggle="tooltip" data-placement="bottom" title="Logout"></span>
   			</a>
	    {%endif%}
	    <center><img id="logo" src="{%static 'img/amazon_logo1.png' %}" /></center>
	    <a href="{% url 'dashboard' %}" class="home_button">
	        <span class="glyphicon glyphicon-home" data-toggle="tooltip" data-placement="bottom" title="Home"></span>
	    </a>
  	</div>
	{% block main_content %}
	{% endblock %}
</body>
</html>